using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.Resources;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using Clear_Choice.Windows;
using ClearChoice;
using ExceptionLogging;
using Stemstudios.DataAccessLayer;
using Stemstudios.DataAccessLayer.DataObjects;
using Stemstudios.DataAccessLayer.DataObjects.Bindings;
using Stemstudios.UIControls;
using System.Text;

namespace Clear_Choice.Views
{
    /// <summary>
    /// Interaction logic for InventoryRecordReport.xaml
    /// </summary>
    public partial class LotLabourCostReport : UserControl,ISTabView
    {
        private Database db = Database.Instance;
        private DataSet itemRecords = null;
        private ResourceManager msgCodes = MessageCodes.ResourceManager;

        public LotLabourCostReport()
        {
            this.Name = "LotLabourCostReport";
            InitializeComponent();
            dpFrom.SelectedDate = DateTime.Now.AddMonths(-1);
            dpTo.SelectedDate = DateTime.Now;
            LoadGrid();
        }

        private void LoadGrid()
        {
            try
            {
                StringBuilder qrySelect = new StringBuilder();
                qrySelect.Append("`lots`.`lotID` AS `lotID`,");
                qrySelect.Append("`lots`.`LotNumber` AS `LotNumber`,");
                qrySelect.Append("`lots`.`Address` AS `Address`,");
                qrySelect.Append("`lots`.`City` AS `City`,");
                qrySelect.Append("sum(`time_sheets`.`Hours`) AS `Hours`,");
                qrySelect.Append("sum((`time_sheets`.`Hours` * `time_sheets`.`Wage`)) AS `LabourCost`");

                DataSet data = db.Select(qrySelect.ToString(), "(`lots` join `time_sheets`)", "((`lots`.`lotID` = `time_sheets`.`lotID`) AND (`time_sheets`.`Date` >= '" + dpFrom.SelectedDate.ToString("yyyy-MM-dd") + "') AND (`time_sheets`.`Date` <= '" + dpTo.SelectedDate.ToString("yyyy-MM-dd") + "')) group by `lots`.`lotID`", "`lots`.`City`,`lots`.`Address`,`lots`.`LotNumber`");
                Collection<LotLabourCostsBinding> gridData = data.getBindableCollection<LotLabourCostsBinding>();
                this.dgLabourHours.ItemsSource = gridData;

                itemRecords = data;
                LoadAverageTotalStats();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loading Lots - " + msgCodes.GetString("M2102") + ex.Message, "Error - 2102", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void dgLots_AutoGeneratedColumns(object sender, EventArgs e)
        {
            Hashtable textMap = LotLabourCostsBinding.GetDisplayTextMap();
            foreach (DataGridColumn column in dgLabourHours.Columns)
            {
                int index = dgLabourHours.Columns.IndexOf(column);
                String headerText = column.Header.ToString();
                if (headerText.Contains("ID"))
                {
                    dgLabourHours.Columns[index].Visibility = System.Windows.Visibility.Collapsed;
                }
                else
                {
                    if (textMap.ContainsKey(headerText))
                    {
                        dgLabourHours.Columns[index].Header = textMap[headerText];
                    }
                }
            }
        }

        private ArrayList Print()
        {
            ArrayList actions = new ArrayList();
            IconButton savenewRepairBtn = new IconButton();
            savenewRepairBtn.Text = "Print";
            savenewRepairBtn.Source = (Image)App.iconSet["printer-icon"];
            savenewRepairBtn.MouseDown += new MouseButtonEventHandler(button1_Click);
            actions.Add(savenewRepairBtn);

            return actions;
        }

        private void button1_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                String title = "Lot Labour Cost Report";
                ArrayList currenyField = new ArrayList();
                ArrayList hiddenColumns = new ArrayList();
                hiddenColumns.Add(Lot.Fields.lotID.ToString());
                currenyField.Add("LabourCost");

                FlowDocument doc = itemRecords.GetFlowDocument(title, hiddenColumns, LotLabourCostsBinding.GetDisplayTextMap(), currenyField);

                DocumentPreviewer preview = new DocumentPreviewer(doc, title);
                preview.ShowDialog();
            }
            catch (Exception)
            {
                MessageBox.Show("Nothing to print", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void LoadAverageTotalStats()
        {
            float totalHours = 0;
            float totalCost = 0;

            while (itemRecords.Read())
            {
                totalHours += Single.Parse(itemRecords.getObject("Hours").ToString());
                totalCost += Single.Parse(itemRecords.getObject("LabourCost").ToString());
            }
            itemRecords.ResetDataSet();
            txtTotalHours.Text = "" + totalHours;
            txtAvgHours.Text = ""+ Single.Parse(""+(totalHours/itemRecords.NumberOfRows())).ToString("#0.00");
            amtTotalCost.Amount = totalCost;
            Math.Round(totalCost);
            amtAvgCost.Amount = (float)Math.Round(totalCost / itemRecords.NumberOfRows(),2);
        }

        private void dgLabourHours_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            if (dgLabourHours.SelectedItem != null)
            {
                LotLabourCostsBinding obj = (LotLabourCostsBinding)dgLabourHours.SelectedItem;
                try
                {
                    DataSet data = db.Select("*", Lot.Table, Lot.Fields.lotID.ToString() + " = '" + obj.lotID + "'");
                    if (data.NumberOfRows() == 1)
                    {
                        data.Read();
                        Lot lot = new Lot(data.GetRecordDataSet());
                        MainWindow.OpenTab(new LotView(lot),(Image)App.iconSet["home"],lot.LotDisplayName());
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error loading selected lot - "+msgCodes.GetString("M2102")+" "+ex.Message,"Error - 2102",MessageBoxButton.OK,MessageBoxImage.Error);
                }
            
            }
        }

        #region ISTabView Members

        public bool TabIsClosing()
        {
            return true;
        }

        public bool TabIsLosingFocus()
        {
            return true;
        }

        public void TabIsGainingFocus()
        {
            MainWindow.setActionList(Print());
        }

        public string TabTitle()
        {
            return "Lot Labour Costs";
        }

        public Image TabIcon()
        {
            return (Image)App.iconSet["clock-icon"];
        }

        #endregion

        private void dpFrom_SelectedDateChanged(object sender, SelectionChangedEventArgs e)
        {
            if (IsLoaded)
            {
                LoadGrid();
            }
        }
    }
}

