using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.Resources;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using Clear_Choice.Windows;
using ClearChoice;
using ExceptionLogging;
using Stemstudios.DataAccessLayer;
using Stemstudios.DataAccessLayer.DataObjects;
using Stemstudios.DataAccessLayer.DataObjects.Bindings;
using Stemstudios.UIControls;
using System.Text;

namespace Clear_Choice.Views
{
    /// <summary>
    /// Interaction logic for InventoryRecordReport.xaml
    /// </summary>
    public partial class LotServicesBilledReport : UserControl,ISTabView
    {
        private Database db = Database.Instance;
        private DataSet itemRecords = null;
        private ResourceManager msgCodes = MessageCodes.ResourceManager;

        public LotServicesBilledReport()
        {
            this.Name = "LotServicesBilledReport";
            InitializeComponent();
            dpFrom.SelectedDate = DateTime.Now.AddMonths(-1);
            dpTo.SelectedDate = DateTime.Now;
            LoadGrid();
        }

        private void LoadGrid()
        {
            try
            {
                StringBuilder selectStatement = new StringBuilder();
                selectStatement.Append("lots.lotID AS lotID,");
                selectStatement.Append("lots.LotNumber AS LotNumber,");
                selectStatement.Append("lots.Address AS Address,");
                selectStatement.Append("lots.City AS City,");
                selectStatement.Append("sum(lot_services.Amount) AS Amount");

                DataSet data = db.Select(selectStatement.ToString(), "lots, lot_services", "lots.lotID = lot_services.lotID and lot_services.Billed is not null and lot_services.Billed >= '" + dpFrom.SelectedDate.ToString("yyyy-MM-dd") + "' and lot_services.Billed <= '" + dpTo.SelectedDate.ToString("yyyy-MM-dd") + "' group by lots.lotID", "lots.City,lots.Address,lots.LotNumber");

                Collection<LotServicesBilledBinding> gridData = data.getBindableCollection<LotServicesBilledBinding>();
                this.dgHours.ItemsSource = gridData;

                itemRecords = data;
                CalculateAvgAndTotal();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loading info - " + msgCodes.GetString("M2102") + ex.Message, "Error - 2102", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void CalculateAvgAndTotal()
        {
            float total = 0;
            while (itemRecords.Read())
            {
                total += Single.Parse(itemRecords.getString("Amount"));
            }
            amtTotalBilled.Amount = total;
            if (total > 0)
            {
                amtLotAvg.Amount = total / itemRecords.NumberOfRows();
            }
            itemRecords.ResetDataSet();
        }

        private void dgLots_AutoGeneratedColumns(object sender, EventArgs e)
        {
            Hashtable textMap = LotServicesBilledBinding.GetDisplayTextMap();
            foreach (DataGridColumn column in dgHours.Columns)
            {
                int index = dgHours.Columns.IndexOf(column);
                String headerText = column.Header.ToString();
                if (headerText.Contains("ID"))
                {
                    dgHours.Columns[index].Visibility = System.Windows.Visibility.Collapsed;
                }
                else
                {
                    if (textMap.ContainsKey(headerText))
                    {
                        dgHours.Columns[index].Header = textMap[headerText];
                    }
                }
            }
        }

        private ArrayList Print()
        {
            ArrayList actions = new ArrayList();
            IconButton savenewRepairBtn = new IconButton();
            savenewRepairBtn.Text = "Print";
            savenewRepairBtn.Source = (Image)App.iconSet["printer-icon"];
            savenewRepairBtn.MouseDown += new MouseButtonEventHandler(button1_Click);
            actions.Add(savenewRepairBtn);


            return actions;
        }

        private void button1_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                String title = "Lot Services Billed Report";
                ArrayList hideFields = new ArrayList();
                ArrayList currenyField = new ArrayList();
                hideFields.Add("lotID");
                currenyField.Add("Amount");
                FlowDocument doc = itemRecords.GetFlowDocument(title, hideFields, LotServicesBilledBinding.GetDisplayTextMap(), currenyField);

                DocumentPreviewer preview = new DocumentPreviewer(doc, title);
                preview.ShowDialog();
            }
            catch (Exception)
            {
                MessageBox.Show("Nothing to print", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void dgHours_MouseDoubleClick(object sender, MouseButtonEventArgs e)
        {
            if (dgHours.SelectedItem != null)
            {
                LotServicesBilledBinding obj = (LotServicesBilledBinding)dgHours.SelectedItem;
                try
                {
                    DataSet data = db.Select("*", Lot.Table, Lot.Fields.lotID.ToString() + " = '" + obj.lotID + "'");
                    if (data.NumberOfRows() == 1)
                    {
                        data.Read();
                        Lot lot = new Lot(data.GetRecordDataSet());
                        MainWindow.OpenTab(new LotView(lot), (Image)App.iconSet["home"], lot.LotDisplayName());
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error loading selected lot - " + msgCodes.GetString("M2102") + " " + ex.Message, "Error - 2102", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }

        #region ISTabView Members

        public bool TabIsClosing()
        {
            return true;
        }

        public bool TabIsLosingFocus()
        {
            return true;
        }

        public void TabIsGainingFocus()
        {
            MainWindow.setActionList(Print());
        }

        public string TabTitle()
        {
            return "Lot Services Billed";
        }

        public Image TabIcon()
        {
            return (Image)App.iconSet["check-icon"];
        }

        #endregion

        private void dpFrom_SelectedDateChanged(object sender, SelectionChangedEventArgs e)
        {
            if (IsLoaded)
            {
                LoadGrid();
            }
        }
    }
}

