using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.Resources;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using ExceptionLogging;
using Stemstudios.DataAccessLayer;
using Stemstudios.DataAccessLayer.DataObjects;
using Stemstudios.DataAccessLayer.DataObjects.Bindings;
using ClearChoice;
using Stemstudios.UIControls;
using System.Windows.Input;
using System.Windows.Documents;
using Clear_Choice.Windows;

namespace Clear_Choice.Views
{
    /// <summary>
    /// Interaction logic for InventoryRecordReport.xaml
    /// </summary>
    public partial class LotSiteMaterialCostReport : UserControl
    {
        private Database db = Database.Instance;
        private DataSet itemRecords = null;
        private ResourceManager msgCodes = MessageCodes.ResourceManager;
        private ComboBoxItem builderItem = new ComboBoxItem();

        public LotSiteMaterialCostReport()
        {
            this.Name = "LotSiteMaterialCostReport";
            InitializeComponent();
            builderItem = (ComboBoxItem)cmboType.SelectedItem;
            LoadGrid();
        }

        private void LoadGrid()
        {
            try
            {
                DataSet data;
                if (cmboType.SelectedItem.Equals(builderItem))
                {
                    data = db.Select("*", "site_material_costs");
                    Collection<SiteMaterialCostsBinding> gridData = data.getBindableCollection<SiteMaterialCostsBinding>();
                    this.dgLabourHours.ItemsSource = gridData;
                }
                else
                {
                    data = db.Select("*","lot_material_costs");
                        Collection<LotMaterialCostsBinding> gridData = data.getBindableCollection<LotMaterialCostsBinding>();
                        this.dgLabourHours.ItemsSource = gridData;
                    
                }
                itemRecords = data;
                LoadAverageTotalStats();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loading Transactions - " + msgCodes.GetString("M2102") + ex.Message, "Error - 2102", MessageBoxButton.OK, MessageBoxImage.Error);
            }   
        }

        private void dgLots_AutoGeneratedColumns(object sender, EventArgs e)
        {
            Hashtable textMap = LotBinding.getdisplayTextMap();
            foreach (DataGridColumn column in dgLabourHours.Columns)
            {
                int index = dgLabourHours.Columns.IndexOf(column);
                String headerText = column.Header.ToString();
                if (headerText.Contains("ID"))
                {
                    dgLabourHours.Columns[index].Visibility = System.Windows.Visibility.Collapsed;
                }
                else
                {
                    if (textMap.ContainsKey(headerText))
                    {
                        dgLabourHours.Columns[index].Header = textMap[headerText];
                    }
                }
            }
        }

        private void UserControl_IsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            if (IsVisible)
            {
                MainWindow.setActionList(Print());
            }
        }

        private ArrayList Print()
        {
            ArrayList actions = new ArrayList();
            IconButton savenewRepairBtn = new IconButton();
            savenewRepairBtn.Text = "Print";
            savenewRepairBtn.Source = (Image)App.iconSet["printer-icon"];
            savenewRepairBtn.MouseDown += new MouseButtonEventHandler(button1_Click);
            actions.Add(savenewRepairBtn);

            return actions;
        }

        private void button1_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                String title;
                ArrayList hideFields = new ArrayList();
                ArrayList currenyField = new ArrayList();
                currenyField.Add("TotalValue");
                FlowDocument doc;
                if(cmboType.SelectedItem.Equals(builderItem))
                {
                    title = "Site Material Costs";
                    doc = itemRecords.GetFlowDocument(title, hideFields, SiteMaterialCostsBinding.GetDisplayTextMap(), currenyField);
                }
                else
                {
                    title = "Lot Material Costs";
                    doc = itemRecords.GetFlowDocument(title, hideFields, LotMaterialCostsBinding.GetDisplayTextMap(), currenyField);
                }

                DocumentPreviewer preview = new DocumentPreviewer(doc, title);
                preview.ShowDialog();
            }
            catch (Exception)
            {
                MessageBox.Show("Nothing to print", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void cmboType_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            if (IsLoaded)
            {
                LoadGrid();
            }
        }

        private void LoadAverageTotalStats()
        {
            float totalQty = 0;
            float totalCost = 0;

            while (itemRecords.Read())
            {
                totalQty += Single.Parse(itemRecords.getObject("Quantity").ToString());
                totalCost += Single.Parse(itemRecords.getObject("TotalValue").ToString());
            }
            itemRecords.ResetDataSet();
            txtTotalQty.Text = "" + totalQty;
            txtAvgQty.Text = "" + Single.Parse("" + (totalQty / itemRecords.NumberOfRows())).ToString("#0.00");
            amtTotalCost.Amount = totalCost;
            Math.Round(totalCost);
            amtAvgCost.Amount = (float)Math.Round(totalCost / itemRecords.NumberOfRows(), 2);
        }
    }
}

