using System;
using System.Collections.ObjectModel;
using System.Resources;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using ExceptionLogging;
using Stemstudios.DataAccessLayer;
using Stemstudios.DataAccessLayer.DataObjects;
using Stemstudios.DataAccessLayer.DataObjects.Bindings;
using ClearChoice;
using System.Collections;

namespace Clear_Choice.Views
{
    /// <summary>
    /// Interaction logic for RepairsCompletedReport.xaml
    /// </summary>
    public partial class ScheduledRepairsView : UserControl
    {
        private Database db = Database.Instance;
        private DataSet itemRecords = null;
        private ResourceManager msgCodes = MessageCodes.ResourceManager;

        public ScheduledRepairsView()
        {
            InitializeComponent();
            this.Name = "ScheduledRepairsView";
            DateTime now = DateTime.Now;
            dpStart.SelectedDate = now;
            dpEnd.SelectedDate = now.AddMonths(1);
            cmdOkay_Click(null, new RoutedEventArgs());
        }

        private void cmdOkay_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                DataSet data = db.Select("*", LotRepair.Table, LotRepair.Fields.DateOfAppointment.ToString() + " between '" + dpStart.SelectedDate.ToString("yyyy-MM-dd HH:mm:ss") + "' and '" + dpEnd.SelectedDate.ToString("yyyy-MM-dd HH:mm:ss") + "'");

                data.BuildPrimaryKeyIndex(LotRepair.PrimaryKey);
                Collection<LotRepairBinding> gridData = data.getBindableCollection<LotRepairBinding>();
                dgRepair.ItemsSource = gridData;

                itemRecords = data;
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loading Repairs - " + msgCodes.GetString("M2102") + ex.Message, "Error - 2102", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void UserControl_IsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            if (IsVisible)
            {
                MainWindow.setActionList(new System.Collections.ArrayList());
            }
        }

        private void dgRepair_AutoGeneratedColumns(object sender, EventArgs e)
        {
            Hashtable textMap = LotRepairBinding.GetDisplayTextMap();
            foreach (DataGridColumn column in dgRepair.Columns)
            {
                int index = dgRepair.Columns.IndexOf(column);
                String headerText = column.Header.ToString();
                if (headerText.Contains("ID"))
                {
                    dgRepair.Columns[index].Visibility = System.Windows.Visibility.Collapsed;
                }
                else
                {
                    if (textMap.ContainsKey(headerText))
                    {
                        dgRepair.Columns[index].Header = textMap[headerText];
                    }
                }
            }
        }

        private void dgRepair_MouseDoubleClick(object sender, System.Windows.Input.MouseButtonEventArgs e)
        {
            if (dgRepair.SelectedItem != null)
            {
                LotRepairBinding obj = (LotRepairBinding)dgRepair.SelectedItem;
                try
                {
                    DataSet data = db.Select("*", LotRepair.Table, LotRepair.Fields.repairID.ToString() + " = '" + obj.repairID + "'");
                    if (data.NumberOfRows() == 1)
                    {
                        data.Read();
                        LotRepair repair = new LotRepair(data.GetRecordDataSet());

                        data = db.Select("*", Lot.Table, Lot.Fields.lotID.ToString() + " = '" + repair.GetLotID() + "'");
                        data.Read();
                        Lot lot = new Lot(data.GetRecordDataSet());

                        MainWindow.OpenTab(new LotRepairView(repair, lot), (Image)App.iconSet["symbol-repair"], repair.GetWorkOrder());
                    }
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error loading selected repair - " + msgCodes.GetString("M2102") + " " + ex.Message, "Error - 2102", MessageBoxButton.OK, MessageBoxImage.Error);
                }
            }
        }
    }
}
