using System;
using System.Collections;
using System.Collections.ObjectModel;
using System.Resources;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Threading;
using ExceptionLogging;
using Stemstudios.DataAccessLayer;
using Stemstudios.DataAccessLayer.DataObjects;
using Stemstudios.DataAccessLayer.DataObjects.Bindings;
using ClearChoice;
using Stemstudios.UIControls;
using System.Windows.Input;
using System.Windows.Documents;
using Clear_Choice.Windows;

namespace Clear_Choice.Views
{
    /// <summary>
    /// Interaction logic for InventoryRecordReport.xaml
    /// </summary>
    public partial class TotalLabourCost : UserControl
    {
        private Database db = Database.Instance;
        private DataSet itemRecords = null;
        private ResourceManager msgCodes = MessageCodes.ResourceManager;

        public TotalLabourCost()
        {
            this.Name = "TotalLabourCost";
            InitializeComponent();
            LoadGrid();
        }

        private void LoadGrid()
        {
            try
            {

                DataSet data = db.Select("lots.LotNumber,lots.Address,lots.City, SUM(time_sheets.Hours) As Hours, SUM(time_sheets.Hours*time_sheets.Wage) As LabourCost", Lot.Table + "," + TimeSheet.Table, "lots.lotID = time_sheets.lotID", "lots.City, lots.Address, lots.LotNumber");
                Collection<TotalLabourBinding> gridData = data.getBindableCollection<TotalLabourBinding>();
                this.dgLabourHours.ItemsSource = gridData;

                itemRecords = data;
                LoadAverageTotalStats();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Loading Lots - " + msgCodes.GetString("M2102") + ex.Message, "Error - 2102", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void dgLots_AutoGeneratedColumns(object sender, EventArgs e)
        {
            Hashtable textMap = LotBinding.getdisplayTextMap();
            foreach (DataGridColumn column in dgLabourHours.Columns)
            {
                int index = dgLabourHours.Columns.IndexOf(column);
                String headerText = column.Header.ToString();
                if (headerText.Contains("ID"))
                {
                    dgLabourHours.Columns[index].Visibility = System.Windows.Visibility.Collapsed;
                }
                else
                {
                    if (textMap.ContainsKey(headerText))
                    {
                        dgLabourHours.Columns[index].Header = textMap[headerText];
                    }
                }
            }
        }

        private void UserControl_IsVisibleChanged(object sender, DependencyPropertyChangedEventArgs e)
        {
            if (IsVisible)
            {
                MainWindow.setActionList(Print());
            }
        }

        private ArrayList Print()
        {
            ArrayList actions = new ArrayList();
            IconButton savenewRepairBtn = new IconButton();
            savenewRepairBtn.Text = "Print";
            savenewRepairBtn.Source = (Image)App.iconSet["symbol-save"];
            savenewRepairBtn.MouseDown += new MouseButtonEventHandler(button1_Click);
            actions.Add(savenewRepairBtn);

            return actions;
        }

        private void button1_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                String title = "Total Labour Report";
                ArrayList currenyField = new ArrayList();
                currenyField.Add("LabourCost");

                FlowDocument doc = itemRecords.GetFlowDocument(title, null, TotalLabourBinding.GetDisplayTextMap(), currenyField);

                DocumentPreviewer preview = new DocumentPreviewer(doc, title);
                preview.ShowDialog();
            }
            catch (Exception)
            {
                MessageBox.Show("Nothing to print", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        private void LoadAverageTotalStats()
        {
            float totalHours = 0;
            float totalCost = 0;

            while (itemRecords.Read())
            {
                totalHours += Single.Parse(itemRecords.getObject("Hours").ToString());
                totalCost += Single.Parse(itemRecords.getObject("LabourCost").ToString());
            }
            itemRecords.ResetDataSet();
            txtTotalHours.Text = "" + totalHours;
            txtAvgHours.Text = ""+ Single.Parse(""+(totalHours/itemRecords.NumberOfRows())).ToString("#0.00");
            amtTotalCost.Amount = totalCost;
            Math.Round(totalCost);
            amtAvgCost.Amount = (float)Math.Round(totalCost / itemRecords.NumberOfRows(),2);
        }
    }
}

