//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExceptionLogging {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExceptionLogging.MessageCodes", typeof(MessageCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is marked as required. Please fill in the field and try again..
        /// </summary>
        public static string M1101 {
            get {
                return ResourceManager.GetString("M1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field contains either a &apos; or a ; These characters are considered invalid and should be removed..
        /// </summary>
        public static string M1102 {
            get {
                return ResourceManager.GetString("M1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field contains characters that are not letters. This field only only accepts letters..
        /// </summary>
        public static string M1103 {
            get {
                return ResourceManager.GetString("M1103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field contains characters other than letters and numbers. This field only accepts letters, numbers, &apos;.&apos;, &apos;-&apos;, &apos;/&apos;, &apos; &apos;, and &apos;+&apos;.
        /// </summary>
        public static string M1104 {
            get {
                return ResourceManager.GetString("M1104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field only accepts a specific format. Please make sure the field resembles (999) 999-999.
        /// </summary>
        public static string M1105 {
            get {
                return ResourceManager.GetString("M1105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field only accepts a specific format. Please make sure the field resembles A5A 5A5.
        /// </summary>
        public static string M1106 {
            get {
                return ResourceManager.GetString("M1106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field only accepts a specific format. Please make sure the field resembles abc@example.com.
        /// </summary>
        public static string M1107 {
            get {
                return ResourceManager.GetString("M1107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field only accepts a number that has no decimal places or characters like $ or ,.
        /// </summary>
        public static string M1108 {
            get {
                return ResourceManager.GetString("M1108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field must be unique. Please confirm the value is correct and unqiue..
        /// </summary>
        public static string M1109 {
            get {
                return ResourceManager.GetString("M1109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load object schema from database. Please contact administrator. Message:.
        /// </summary>
        public static string M2101 {
            get {
                return ResourceManager.GetString("M2101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database interaction failed. Please contact system administrator. Message:.
        /// </summary>
        public static string M2102 {
            get {
                return ResourceManager.GetString("M2102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to add a new object to the system. Are you sure you want to continue?.
        /// </summary>
        public static string M3201 {
            get {
                return ResourceManager.GetString("M3201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to save your modifications to this object. Are you sure you want to continue?.
        /// </summary>
        public static string M3202 {
            get {
                return ResourceManager.GetString("M3202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object may already exist in the system. Please confirm the following fields are unique:.
        /// </summary>
        public static string M3203 {
            get {
                return ResourceManager.GetString("M3203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to cancel adding a new object. Are you sure you want to continue?.
        /// </summary>
        public static string M3204 {
            get {
                return ResourceManager.GetString("M3204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to cancel the modifications made to the object. Are you sure you want to continue?.
        /// </summary>
        public static string M3205 {
            get {
                return ResourceManager.GetString("M3205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item will have a Quantity of 0 if you commit this transaction. This will cause the average cost to be exactly the same as the Latest cost and may provide inaccurate reporting..
        /// </summary>
        public static string M3206 {
            get {
                return ResourceManager.GetString("M3206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tab is considered  a transactional tab and requires that you either Save or Cancel you changes to the current object before selecting a new tab..
        /// </summary>
        public static string M3207 {
            get {
                return ResourceManager.GetString("M3207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to replace the accounts current password with a new random password. Are you sure you want to continue?.
        /// </summary>
        public static string M4201 {
            get {
                return ResourceManager.GetString("M4201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to grant access to this site via the web portal. Are you sure you want to continue?.
        /// </summary>
        public static string M4202 {
            get {
                return ResourceManager.GetString("M4202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to remove access to this site via the web portal. Are you sure you want to continue?.
        /// </summary>
        public static string M4203 {
            get {
                return ResourceManager.GetString("M4203", resourceCulture);
            }
        }
    }
}
